# Generated by Django 4.2.6 on 2024-03-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issuedate', models.DateField()),
                ('returndate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
