# Generated by Django 4.2.6 on 2024-03-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0004_rent_book_rent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='Issuedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
