# Generated by Django 4.2.6 on 2024-03-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0005_alter_rent_issuedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
