# Generated by Django 4.2.6 on 2024-03-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0008_requestbook_issued_requestbook_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
