# Generated by Django 4.2.6 on 2024-03-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0011_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
