# Generated by Django 4.2.6 on 2024-03-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0012_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
