# Generated by Django 4.2.6 on 2024-03-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0014_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
