# Generated by Django 4.2.6 on 2024-03-16 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0015_requestbook_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='requestbook',
        ),
        migrations.AddField(
            model_name='lost',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vookeys.book'),
        ),
    ]
