# Generated by Django 4.2.6 on 2024-03-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0016_remove_lost_requestbook_lost_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='damage',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
