# Generated by Django 4.2.6 on 2024-03-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0017_lost_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='fine',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
