# Generated by Django 4.2.6 on 2024-03-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0022_bookfine'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfine',
            name='diff',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
