# Generated by Django 4.2.6 on 2024-03-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0023_bookfine_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='diff',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
