# Generated by Django 4.2.6 on 2024-03-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0024_requestbook_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
