# Generated by Django 4.2.6 on 2024-03-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0025_requestbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfine',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
