# Generated by Django 4.2.6 on 2024-03-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0026_bookfine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
