# Generated by Django 4.2.6 on 2024-04-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0028_issuebook_diff_issuebook_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
