# Generated by Django 4.2.6 on 2024-04-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0029_issuebook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='bookfine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lost',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
