# Generated by Django 4.2.6 on 2024-04-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vookeys', '0031_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='calc',
            field=models.BooleanField(default=False),
        ),
    ]
